services:

- type: web

  repo: https://github.com/ashokpds15/test

  name: test

  plan: free

  branch: main

  rootDir: .

  region: singapore

  env: python

  buildCommand: pip install -r requirements.txt
buildCommand: pip install --upgrade pip
  startCommand: python main.py
  
